import { useMemo, useRef, useState } from "react";
import { Home, Users, ReceiptText, Plus, X, Wallet, Trash2, Check, UserPlus, Download, Upload } from "lucide-react";

type Person = { id: string; name: string; email?: string };
type Group = { id: string; name: string; members: string[] };
type Expense = { id: string; title: string; amount: number; paidBy: string; people: string[]; groupId: string; createdAt: number; splitMode?: "equal"|"exact"|"percent"; shares?: Record<string,number> };
type Payment = { id: string; from: string; to: string; amount: number; createdAt: number };
const me = "You";
const initialPeople: Person[] = [{id:"you",name:me},{id:"alex",name:"Alex"},{id:"sam",name:"Sam"},{id:"jordan",name:"Jordan"}];
const initialGroups: Group[] = [{id:"apartment",name:"Apartment",members:["you","alex","sam"]},{id:"goa",name:"Goa trip",members:["you","alex","sam","jordan"]}];
const load = <T,>(key:string, fallback:T):T => { try { const v=localStorage.getItem("swp_"+key); return v ? JSON.parse(v) as T : fallback; } catch { return fallback; } };
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n);
export default function App(){
 const [tab,setTab]=useState("Home");
 const [expenseSearch,setExpenseSearch]=useState(""); const [expenseGroupFilter,setExpenseGroupFilter]=useState("all"); const [expenseDateFilter,setExpenseDateFilter]=useState("all"); const [expenseSort,setExpenseSort]=useState("newest");
 const [people,setPeople]=useState<Person[]>(()=>load("people",initialPeople));
 const [groups,setGroups]=useState<Group[]>(()=>load("groups",initialGroups));
 const [expenses,setExpenses]=useState<Expense[]>(()=>{const raw=load<any[]>("expenses",[]);const ids:Record<string,string>={You:"you",Alex:"alex",Sam:"sam",Jordan:"jordan"};return raw.map((e:any)=>({id:String(e.id??crypto.randomUUID()),title:String(e.title??"Expense"),amount:Number(e.amount)||0,paidBy:ids[e.paidBy]||e.paidBy||"you",people:Array.isArray(e.people)?e.people.map((p:string)=>ids[p]||p):["you"],groupId:groups.find(g=>g.name===(e.group||e.groupId))?.id||"apartment",createdAt:Number(e.createdAt)||Number(e.id)||Date.now(),splitMode:e.splitMode||"equal",shares:e.shares||{}}));});
 const [payments,setPayments]=useState<Payment[]>(()=>load("payments",[]));
 const [modal,setModal]=useState<"expense"|"friend"|"group"|"settle"|null>(null);
 const restoreInputRef=useRef<HTMLInputElement>(null);
 const [title,setTitle]=useState(""); const [amount,setAmount]=useState(""); const [splitMode,setSplitMode]=useState<"equal"|"exact"|"percent">("equal"); const [shares,setShares]=useState<Record<string,string>>({}); const [editingId,setEditingId]=useState<string|null>(null); const [paidBy,setPaidBy]=useState("you"); const [groupId,setGroupId]=useState("apartment"); const [selected,setSelected]=useState<string[]>(["you","alex","sam"]);
 const [friendName,setFriendName]=useState(""); const [friendEmail,setFriendEmail]=useState(""); const [groupName,setGroupName]=useState(""); const [editingGroupId,setEditingGroupId]=useState<string|null>(null); const [groupMembers,setGroupMembers]=useState<string[]>([]); const [settleFrom,setSettleFrom]=useState("alex"); const [settleTo,setSettleTo]=useState("you");
 const persist=(key:string,value:unknown)=>localStorage.setItem("swp_"+key,JSON.stringify(value));
 const person=(id:string)=>people.find(p=>p.id===id)?.name||"Unknown";
 const group=(id:string)=>groups.find(g=>g.id===id)?.name||"No group";
 const total=expenses.reduce((s,e)=>s+e.amount,0);
 const filteredExpenses=useMemo(()=>{const q=expenseSearch.trim().toLowerCase();const now=new Date();return expenses.filter(e=>{const d=new Date(e.createdAt);const matchesText=!q||[e.title,person(e.paidBy),group(e.groupId),...e.people.map(person)].some(v=>v.toLowerCase().includes(q));const matchesGroup=expenseGroupFilter==="all"||e.groupId===expenseGroupFilter;const matchesDate=expenseDateFilter==="all"||(expenseDateFilter==="month"&&d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth())||(expenseDateFilter==="year"&&d.getFullYear()===now.getFullYear());return matchesText&&matchesGroup&&matchesDate;}).sort((a,b)=>expenseSort==="oldest"?a.createdAt-b.createdAt:expenseSort==="amount"?b.amount-a.amount:b.createdAt-a.createdAt);},[expenses,expenseSearch,expenseGroupFilter,expenseDateFilter,expenseSort,people,groups]);
 const balances=useMemo(()=>{const b:Record<string,number>={};people.forEach(p=>b[p.id]=0);expenses.forEach(e=>{if(!e.people.length)return;b[e.paidBy]=(b[e.paidBy]||0)+e.amount;const split=e.splitMode||"equal";e.people.forEach(id=>{const share=split==="equal"?e.amount/e.people.length:Number(e.shares?.[id]??0);b[id]=(b[id]||0)-share;});});payments.forEach(p=>{b[p.from]=(b[p.from]||0)+p.amount;b[p.to]=(b[p.to]||0)-p.amount});return b;},[people,expenses,payments]);
 const saveExpense=()=>{const n=Number(amount);if(!title.trim()||!Number.isFinite(n)||n<=0||selected.length===0)return;let splitShares:Record<string,number>={};if(splitMode!=="equal"){const vals=selected.map(id=>Number(shares[id]||0));if(vals.some(v=>!Number.isFinite(v)||v<0))return;const sum=vals.reduce((a,b)=>a+b,0);if(splitMode==="exact"&&Math.abs(sum-n)>.01)return;if(splitMode==="percent"&&Math.abs(sum-100)>.01)return;selected.forEach((id,i)=>splitShares[id]=splitMode==="percent"?n*vals[i]/100:vals[i]);}const old=expenses.find(e=>e.id===editingId);const e:Expense={id:editingId||crypto.randomUUID(),title:title.trim(),amount:n,paidBy,people:selected,groupId,createdAt:old?.createdAt||Date.now(),splitMode,shares:splitShares};const next=editingId?expenses.map(x=>x.id===editingId?e:x):[e,...expenses];setExpenses(next);persist("expenses",next);setTitle("");setAmount("");setEditingId(null);setSplitMode("equal");setShares({});setModal(null);};
 const addFriend=()=>{const name=friendName.trim();if(!name)return;const p={id:crypto.randomUUID(),name};const next=[...people,p];setPeople(next);persist("people",next);setFriendName("");setModal(null);};
 const openGroup=(g?:Group)=>{setEditingGroupId(g?.id||null);setGroupName(g?.name||"");setGroupMembers(g?[...g.members]:people.map(p=>p.id));setModal("group");}; const addGroup=()=>{const name=groupName.trim();if(!name||groupMembers.length===0)return;const next=editingGroupId?groups.map(g=>g.id===editingGroupId?{...g,name,members:groupMembers}:g):[...groups,{id:crypto.randomUUID(),name,members:groupMembers}];setGroups(next);persist("groups",next);setGroupName("");setEditingGroupId(null);setGroupMembers([]);setModal(null);}; const deleteGroup=(id:string)=>{if(groups.length<=1){alert("Keep at least one group.");return;}if(!confirm("Delete this group? Existing expenses will remain in history."))return;const next=groups.filter(g=>g.id!==id);setGroups(next);persist("groups",next);};
 const settle=()=>{const n=Number(amount);if(!Number.isFinite(n)||n<=0||settleFrom===settleTo)return;const next=[{id:crypto.randomUUID(),from:settleFrom,to:settleTo,amount:n,createdAt:Date.now()},...payments];setPayments(next);persist("payments",next);setAmount("");setModal(null);};
 const removeExpense=(id:string)=>{const next=expenses.filter(e=>e.id!==id);setExpenses(next);persist("expenses",next);};
 const exportBackup=()=>{
  const backup={version:1,app:"Splitwise",exportedAt:new Date().toISOString(),people,groups,expenses,payments};
  const blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"});
  const url=URL.createObjectURL(blob); const a=document.createElement("a");
  a.href=url; a.download=`splitwise-backup-${new Date().toISOString().slice(0,10)}.json`;
  document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
 };
 const restoreBackup=(file:File)=>{
  const reader=new FileReader();
  reader.onload=()=>{
   try{
    const data=JSON.parse(String(reader.result));
    if(!data||data.version!==1||!Array.isArray(data.people)||!Array.isArray(data.groups)||!Array.isArray(data.expenses)||!Array.isArray(data.payments)) throw new Error("Invalid backup");
    if(!confirm("Restore this backup? Your current groups, friends, expenses, and settlements will be replaced.")) return;
    setPeople(data.people); setGroups(data.groups); setExpenses(data.expenses); setPayments(data.payments);
    persist("people",data.people); persist("groups",data.groups); persist("expenses",data.expenses); persist("payments",data.payments);
    alert("Backup restored successfully.");
   }catch{ alert("This file is not a valid Splitwise backup."); }
  };
  reader.readAsText(file);
 };
 const openExpense=()=>{setEditingId(null);setTitle("");setAmount("");setPaidBy("you");setGroupId(groups[0]?.id||"");setSelected(groups[0]?.members||people.map(p=>p.id));setSplitMode("equal");setShares({});setModal("expense");}; const editExpense=(e:Expense)=>{setEditingId(e.id);setTitle(e.title);setAmount(String(e.amount));setPaidBy(e.paidBy);setGroupId(e.groupId);setSelected(e.people);setSplitMode(e.splitMode||"equal");setShares(Object.fromEntries(e.people.map(id=>[id,String(e.splitMode==="percent"?(e.shares?.[id]||0)*100/e.amount:(e.shares?.[id]??0))])));setModal("expense");};
 const debtors=people.filter(p=>(balances[p.id]||0)<-.005), creditors=people.filter(p=>(balances[p.id]||0)>.005);
 const nav=[{n:"Home",I:Home},{n:"Groups",I:Users},{n:"Activity",I:ReceiptText},{n:"Friends",I:Users},{n:"Balances",I:Wallet}];
 return <div className="app"><header><div className="logo"><b>S</b> Splitwise</div><span className="avatar">Y</span></header><main>
 <p className="eyebrow">YOUR EXPENSES</p><h1>{tab==="Home"?"Hey, You":tab}</h1><p className="muted">Keep track of shared expenses, simply.</p>
 {tab==="Home"&&<><section className="balance"><small>TOTAL SHARED EXPENSES</small><h2>{money(total)}</h2><p>{expenses.length} expenses · saved on this device</p></section><div className="section"><h3>Balances</h3><button className="link" onClick={()=>setTab("Balances")}>Details</button></div>
 <div className="section"><h3>Backup & Restore</h3></div>
 <button className="add" onClick={exportBackup}><Download size={18}/> Export backup</button>
 <button className="add" onClick={()=>restoreInputRef.current?.click()}><Upload size={18}/> Restore backup</button>
 <input ref={restoreInputRef} type="file" accept="application/json,.json" hidden onChange={e=>{const file=e.target.files?.[0];if(file)restoreBackup(file);e.currentTarget.value="";}}/>{people.filter(p=>p.id!=="you").map(p=><div className="tile" key={p.id}><span className="friend">{p.name[0]?.toUpperCase()}</span><div className="grow"><b>{p.name}</b><p>{Math.abs(balances[p.id]||0)<.005?"All settled":(balances[p.id]>0?"owes you ":"you owe ")+money(Math.abs(balances[p.id]||0))}</p></div></div>)}<div className="section"><h3>Recent expenses</h3><button className="link" onClick={()=>setTab("Activity")}>See all</button></div><ExpenseList expenses={expenses.slice(0,4)} person={person} group={group} remove={removeExpense} edit={editExpense}/></>}
 {tab==="Activity"&&<><div className="section"><h3>All expenses</h3><span className="muted">{filteredExpenses.length} of {expenses.length}</span></div><input aria-label="Search expenses" value={expenseSearch} onChange={e=>setExpenseSearch(e.target.value)} placeholder="Search description, person..."/><div className="filters"><select aria-label="Filter by group" value={expenseGroupFilter} onChange={e=>setExpenseGroupFilter(e.target.value)}><option value="all">All groups</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select aria-label="Filter by date" value={expenseDateFilter} onChange={e=>setExpenseDateFilter(e.target.value)}><option value="all">Any date</option><option value="month">This month</option><option value="year">This year</option></select><select aria-label="Sort expenses" value={expenseSort} onChange={e=>setExpenseSort(e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="amount">Highest amount</option></select></div><ExpenseList expenses={filteredExpenses} person={person} group={group} remove={removeExpense} edit={editExpense}/><div className="section"><h3>Settlements</h3></div>{payments.map(p=><div className="expense" key={p.id}><div className="date"><Check size={18}/></div><div className="grow"><b>Settlement</b><p>{person(p.from)} paid {person(p.to)}</p></div><strong>{money(p.amount)}</strong></div>)}</>}
 {tab==="Groups"&&<>{groups.map(g=><div className="tile" key={g.id}><Users/><div className="grow"><b>{g.name}</b><p>{g.members.map(person).join(", ")}</p><p>{g.members.length} members</p></div><button className="link" onClick={()=>openGroup(g)}>Manage</button><button className="iconbtn" aria-label="Delete group" onClick={()=>deleteGroup(g.id)}><Trash2 size={16}/></button></div>)}<button className="add" onClick={()=>openGroup()}><Plus size={18}/> Create group</button></>}
 {tab==="Friends"&&<>{people.map(p=><div className="tile" key={p.id}><span className="friend">{p.name[0]?.toUpperCase()}</span><div className="grow"><b>{p.name}</b><p>{p.id==="you"?"Your account":(balances[p.id]||0)>.005?"Owes you "+money(balances[p.id]):(balances[p.id]||0)<-.005?"You owe "+money(-balances[p.id]):"Settled up"}</p></div></div>)}<button className="add" onClick={()=>setModal("friend")}><UserPlus size={18}/> Add a friend</button></>}
 {tab==="Balances"&&<><section className="balance"><small>YOUR NET BALANCE</small><h2>{money(balances.you||0)}</h2><p>Positive means you are owed; negative means you owe.</p></section><h3>People who owe</h3>{creditors.map(p=><div className="tile" key={p.id}><div className="grow"><b>{person(p.id)}</b></div><strong>{money(balances[p.id])}</strong><button className="link" onClick={()=>{setSettleFrom("you");setSettleTo(p.id);setAmount(String(balances[p.id].toFixed(2)));setModal("settle")}}>Settle</button></div>)}<h3>People you owe</h3>{debtors.map(p=><div className="tile" key={p.id}><div className="grow"><b>{person(p.id)}</b></div><strong>{money(-balances[p.id])}</strong><button className="link" onClick={()=>{setSettleFrom(p.id);setSettleTo("you");setAmount(String((-balances[p.id]).toFixed(2)));setModal("settle")}}>Settle</button></div>)}</>}
 {tab==="Stats"&&<section className="balance"><small>ALL-TIME SPENDING</small><h2>{money(total)}</h2><p>Across {expenses.length} expenses</p></section>}
 <button className="add" onClick={openExpense}><Plus size={19}/> Add an expense</button>
 </main><nav>{nav.map(({n,I})=><button className={tab===n?"active":""} onClick={()=>setTab(n)} key={n}><I/><span>{n}</span></button>)}</nav>
 {modal&&<div className="overlay"><section className="sheet"><div className="sheethead"><h2>{modal==="expense"?(editingId?"Edit expense":"Add an expense"):modal==="friend"?"Add a friend":modal==="group"?"Create a group":"Record settlement"}</h2><button className="close" onClick={()=>setModal(null)}><X/></button></div>
 {modal==="expense"&&<><label>Description</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What was it for?"/><label>Amount (₹)</label><input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/><label>Paid by</label><select value={paidBy} onChange={e=>setPaidBy(e.target.value)}>{people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><label>Group</label><select value={groupId} onChange={e=>{setGroupId(e.target.value);setSelected(groups.find(g=>g.id===e.target.value)?.members||[])}}>{groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><label>Split type</label><select value={splitMode} onChange={e=>setSplitMode(e.target.value as "equal"|"exact"|"percent")}><option value="equal">Equally</option><option value="exact">Exact amounts</option><option value="percent">Percentages</option></select><label>{splitMode==="equal"?"Split equally between":splitMode==="exact"?"Share amount for each person (₹)":"Share percentage for each person (%)"}</label><div className="checks">{people.map(p=><label className="check" key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/>{p.name}{splitMode!=="equal"&&<input className="share-input" type="number" min="0" value={shares[p.id]||""} placeholder={splitMode==="percent"?"%":"₹"} onChange={e=>setShares({...shares,[p.id]:e.target.value})}/>}</label>)}</div><p className="muted">{splitMode==="equal"?"Each selected person gets an equal share.":splitMode==="exact"?"Exact shares must add up to the expense total.":"Percentages must add up to 100%."} Saved on this device.</p><button className="save" onClick={saveExpense}><Check/> Save expense</button></>}
 {modal==="friend"&&<><label>Friend's name</label><input value={friendName} onChange={e=>setFriendName(e.target.value)} placeholder="Name"/><button className="save" onClick={addFriend}>Add friend</button></>}
 {modal==="group"&&<><label>Group name</label><input value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="e.g. Weekend trip"/><label>Members</label><div className="checks">{people.map(p=><label className="check" key={p.id}><input type="checkbox" checked={groupMembers.includes(p.id)} onChange={e=>setGroupMembers(e.target.checked?[...groupMembers,p.id]:groupMembers.filter(id=>id!==p.id))}/>{p.name}</label>)}</div><p className="muted">Choose who belongs to this group. Existing expenses are preserved when you edit membership.</p><button className="save" onClick={addGroup}>{editingGroupId?"Save group":"Create group"}</button></>}
 {modal==="settle"&&<><label>From</label><select value={settleFrom} onChange={e=>setSettleFrom(e.target.value)}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><label>To</label><select value={settleTo} onChange={e=>setSettleTo(e.target.value)}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><label>Amount (₹)</label><input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="save" onClick={settle}><Check/> Record payment</button></>}
 </section></div>}</div>
}
function ExpenseList({expenses,person,group,remove,edit}:{expenses:Expense[];person:(id:string)=>string;group:(id:string)=>string;remove:(id:string)=>void;edit:(e:Expense)=>void}){return <div>{expenses.map(e=><div className="expense" key={e.id}><div className="date"><small>{new Date(e.createdAt).toLocaleDateString("en",{month:"short"})}</small><b>{new Date(e.createdAt).getDate()}</b></div><div className="grow"><b>{e.title}</b><p>{group(e.groupId)} · {person(e.paidBy)} paid · split {e.people.length} ways</p></div><strong>{money(e.amount)}</strong><button className="iconbtn" aria-label="Edit expense" onClick={()=>{edit(e)}}><ReceiptText size={16}/></button><button className="iconbtn" aria-label="Delete expense" onClick={()=>{if(confirm("Delete this expense?"))remove(e.id)}}><Trash2 size={16}/></button></div>)}</div>}
