/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Advance = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'labourId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'amount' : IDL.Float64,
  'contractId' : IDL.Nat,
});
export const WorkColumn = IDL.Record({
  'id' : IDL.Text,
  'workType' : IDL.Text,
  'name' : IDL.Text,
});
export const Contract = IDL.Record({
  'id' : IDL.Nat,
  'multiplier' : IDL.Float64,
  'settled' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'bedAmount' : IDL.Float64,
  'paperAmount' : IDL.Float64,
  'machineExpenses' : IDL.Float64,
  'meshAmount' : IDL.Float64,
  'contractAmount' : IDL.Float64,
  'workColumns' : IDL.Vec(WorkColumn),
});
export const Labour = IDL.Record({
  'id' : IDL.Nat,
  'joinDate' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'employeeId' : IDL.Text,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'contractOnly' : IDL.Null,
  'attendanceOnly' : IDL.Null,
  'viewOnly' : IDL.Null,
});
export const AttendanceValue = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
  'partial' : IDL.Float64,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AttendanceRecord = IDL.Record({
  'value' : AttendanceValue,
  'labourId' : IDL.Nat,
  'contractId' : IDL.Nat,
  'columnId' : IDL.Text,
});
export const UserStatus = IDL.Variant({
  'revoked' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const UserInfo = IDL.Record({
  'status' : UserStatus,
  'username' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
  'role' : Role,
  'email' : IDL.Opt(IDL.Text),
});
export const Credentials = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
});
export const AuthResult = IDL.Record({
  'status' : UserStatus,
  'username' : IDL.Text,
  'role' : Role,
});

export const idlService = IDL.Service({
  'addAdvance' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : Advance, 'err' : IDL.Text })],
      [],
    ),
  'addContract' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
      [],
    ),
  'addLabour' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Labour, 'err' : IDL.Text })],
      [],
    ),
  'addWorkColumn' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
      [],
    ),
  'approveUser' : IDL.Func([IDL.Text, Role], [], []),
  'batchSaveAttendance' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Text, AttendanceValue))],
      [IDL.Vec(IDL.Bool)],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Bool], []),
  'deleteAdvance' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteContract' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'exportData' : IDL.Func([], [IDL.Text], ['query']),
  'getActiveLabours' : IDL.Func([], [IDL.Vec(Labour)], ['query']),
  'getAdvances' : IDL.Func([], [IDL.Vec(Advance)], ['query']),
  'getAdvancesByContract' : IDL.Func([IDL.Nat], [IDL.Vec(Advance)], ['query']),
  'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getAttendance' : IDL.Func([IDL.Nat], [IDL.Vec(AttendanceRecord)], ['query']),
  'getCallerRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getCallerStatus' : IDL.Func([], [UserStatus], ['query']),
  'getContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getLabours' : IDL.Func([], [IDL.Vec(Labour)], ['query']),
  'importData' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'login' : IDL.Func([Credentials], [IDL.Opt(AuthResult)], []),
  'logout' : IDL.Func([], [], []),
  'markContractSettled' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
      [],
    ),
  'removeWorkColumn' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
      [],
    ),
  'revokeAccess' : IDL.Func([IDL.Text], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setAttendance' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, AttendanceValue],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'setUserRole' : IDL.Func([IDL.Text, Role], [], []),
  'updateAdvance' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : Advance, 'err' : IDL.Text })],
      [],
    ),
  'updateContract' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
      [],
    ),
  'updateLabour' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : Labour, 'err' : IDL.Text })],
      [],
    ),
  'updateUserCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateWorkColumn' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Advance = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'labourId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'amount' : IDL.Float64,
    'contractId' : IDL.Nat,
  });
  const WorkColumn = IDL.Record({
    'id' : IDL.Text,
    'workType' : IDL.Text,
    'name' : IDL.Text,
  });
  const Contract = IDL.Record({
    'id' : IDL.Nat,
    'multiplier' : IDL.Float64,
    'settled' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'bedAmount' : IDL.Float64,
    'paperAmount' : IDL.Float64,
    'machineExpenses' : IDL.Float64,
    'meshAmount' : IDL.Float64,
    'contractAmount' : IDL.Float64,
    'workColumns' : IDL.Vec(WorkColumn),
  });
  const Labour = IDL.Record({
    'id' : IDL.Nat,
    'joinDate' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'employeeId' : IDL.Text,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'contractOnly' : IDL.Null,
    'attendanceOnly' : IDL.Null,
    'viewOnly' : IDL.Null,
  });
  const AttendanceValue = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
    'partial' : IDL.Float64,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AttendanceRecord = IDL.Record({
    'value' : AttendanceValue,
    'labourId' : IDL.Nat,
    'contractId' : IDL.Nat,
    'columnId' : IDL.Text,
  });
  const UserStatus = IDL.Variant({
    'revoked' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const UserInfo = IDL.Record({
    'status' : UserStatus,
    'username' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
    'role' : Role,
    'email' : IDL.Opt(IDL.Text),
  });
  const Credentials = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
  });
  const AuthResult = IDL.Record({
    'status' : UserStatus,
    'username' : IDL.Text,
    'role' : Role,
  });
  
  return IDL.Service({
    'addAdvance' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : Advance, 'err' : IDL.Text })],
        [],
      ),
    'addContract' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
        [],
      ),
    'addLabour' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Labour, 'err' : IDL.Text })],
        [],
      ),
    'addWorkColumn' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
        [],
      ),
    'approveUser' : IDL.Func([IDL.Text, Role], [], []),
    'batchSaveAttendance' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Text, AttendanceValue))],
        [IDL.Vec(IDL.Bool)],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Bool], []),
    'deleteAdvance' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteContract' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'exportData' : IDL.Func([], [IDL.Text], ['query']),
    'getActiveLabours' : IDL.Func([], [IDL.Vec(Labour)], ['query']),
    'getAdvances' : IDL.Func([], [IDL.Vec(Advance)], ['query']),
    'getAdvancesByContract' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Advance)],
        ['query'],
      ),
    'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getAttendance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getCallerStatus' : IDL.Func([], [UserStatus], ['query']),
    'getContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getLabours' : IDL.Func([], [IDL.Vec(Labour)], ['query']),
    'importData' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'login' : IDL.Func([Credentials], [IDL.Opt(AuthResult)], []),
    'logout' : IDL.Func([], [], []),
    'markContractSettled' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
        [],
      ),
    'removeWorkColumn' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
        [],
      ),
    'revokeAccess' : IDL.Func([IDL.Text], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setAttendance' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, AttendanceValue],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'setUserRole' : IDL.Func([IDL.Text, Role], [], []),
    'updateAdvance' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : Advance, 'err' : IDL.Text })],
        [],
      ),
    'updateContract' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
        [],
      ),
    'updateLabour' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : Labour, 'err' : IDL.Text })],
        [],
      ),
    'updateUserCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateWorkColumn' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Contract, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };