/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Advance {
  'id' : bigint,
  'note' : string,
  'labourId' : bigint,
  'createdAt' : bigint,
  'amount' : number,
  'contractId' : bigint,
}
export interface AttendanceRecord {
  'value' : AttendanceValue,
  'labourId' : bigint,
  'contractId' : bigint,
  'columnId' : string,
}
export type AttendanceValue = { 'present' : null } |
  { 'absent' : null } |
  { 'partial' : number };
export interface AuthResult {
  'status' : UserStatus,
  'username' : string,
  'role' : Role,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Contract {
  'id' : bigint,
  'multiplier' : number,
  'settled' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'bedAmount' : number,
  'paperAmount' : number,
  'machineExpenses' : number,
  'meshAmount' : number,
  'contractAmount' : number,
  'workColumns' : Array<WorkColumn>,
}
export interface Credentials { 'username' : string, 'password' : string }
export interface Labour {
  'id' : bigint,
  'joinDate' : string,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'employeeId' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Role = { 'admin' : null } |
  { 'contractOnly' : null } |
  { 'attendanceOnly' : null } |
  { 'viewOnly' : null };
export interface UserInfo {
  'status' : UserStatus,
  'username' : string,
  'name' : [] | [string],
  'role' : Role,
  'email' : [] | [string],
}
export type UserStatus = { 'revoked' : null } |
  { 'pending' : null } |
  { 'approved' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WorkColumn {
  'id' : string,
  'workType' : string,
  'name' : string,
}
export interface _SERVICE {
  'addAdvance' : ActorMethod<
    [bigint, bigint, number, string],
    { 'ok' : Advance } |
      { 'err' : string }
  >,
  'addContract' : ActorMethod<
    [string, number, number, number, number, number, [] | [number]],
    { 'ok' : Contract } |
      { 'err' : string }
  >,
  'addLabour' : ActorMethod<
    [string, string, string],
    { 'ok' : Labour } |
      { 'err' : string }
  >,
  'addWorkColumn' : ActorMethod<
    [bigint, string, string],
    { 'ok' : Contract } |
      { 'err' : string }
  >,
  'approveUser' : ActorMethod<[string, Role], undefined>,
  'batchSaveAttendance' : ActorMethod<
    [Array<[bigint, bigint, string, AttendanceValue]>],
    Array<boolean>
  >,
  'createUser' : ActorMethod<[string, string, Role], boolean>,
  'deleteAdvance' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteContract' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'execute' : ActorMethod<[string], Result>,
  'exportData' : ActorMethod<[], string>,
  'getActiveLabours' : ActorMethod<[], Array<Labour>>,
  'getAdvances' : ActorMethod<[], Array<Advance>>,
  'getAdvancesByContract' : ActorMethod<[bigint], Array<Advance>>,
  'getAllAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAttendance' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getCallerRole' : ActorMethod<[], [] | [Role]>,
  'getCallerStatus' : ActorMethod<[], UserStatus>,
  'getContracts' : ActorMethod<[], Array<Contract>>,
  'getLabours' : ActorMethod<[], Array<Labour>>,
  'importData' : ActorMethod<[string], { 'ok' : boolean } | { 'err' : string }>,
  'listUsers' : ActorMethod<[], Array<UserInfo>>,
  'login' : ActorMethod<[Credentials], [] | [AuthResult]>,
  'logout' : ActorMethod<[], undefined>,
  'markContractSettled' : ActorMethod<
    [bigint, boolean],
    { 'ok' : Contract } |
      { 'err' : string }
  >,
  'removeWorkColumn' : ActorMethod<
    [bigint, string],
    { 'ok' : Contract } |
      { 'err' : string }
  >,
  'revokeAccess' : ActorMethod<[string], undefined>,
  'schema' : ActorMethod<[], string>,
  'setAttendance' : ActorMethod<
    [bigint, bigint, string, AttendanceValue],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'setUserRole' : ActorMethod<[string, Role], undefined>,
  'updateAdvance' : ActorMethod<
    [bigint, number, string],
    { 'ok' : Advance } |
      { 'err' : string }
  >,
  'updateContract' : ActorMethod<
    [bigint, string, number, number, number, number, number, [] | [number]],
    { 'ok' : Contract } |
      { 'err' : string }
  >,
  'updateLabour' : ActorMethod<
    [bigint, string, string, string, boolean],
    { 'ok' : Labour } |
      { 'err' : string }
  >,
  'updateUserCredentials' : ActorMethod<
    [string, string, [] | [string]],
    boolean
  >,
  'updateWorkColumn' : ActorMethod<
    [bigint, string, string],
    { 'ok' : Contract } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];