/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Labour {
    id: bigint;
    joinDate: string;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    employeeId: string;
}
export interface Credentials {
    username: string;
    password: string;
}
export interface UserInfo {
    status: UserStatus;
    username: string;
    name?: string;
    role: Role;
    email?: string;
}
export type AttendanceValue = {
    __kind__: "present";
    present: null;
} | {
    __kind__: "absent";
    absent: null;
} | {
    __kind__: "partial";
    partial: number;
};
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface WorkColumn {
    id: string;
    workType: string;
    name: string;
}
export interface AttendanceRecord {
    value: AttendanceValue;
    labourId: bigint;
    contractId: bigint;
    columnId: string;
}
export interface AuthResult {
    status: UserStatus;
    username: string;
    role: Role;
}
export interface Advance {
    id: bigint;
    note: string;
    labourId: bigint;
    createdAt: bigint;
    amount: number;
    contractId: bigint;
}
export interface Contract {
    id: bigint;
    multiplier: number;
    settled: boolean;
    name: string;
    createdAt: bigint;
    bedAmount: number;
    paperAmount: number;
    machineExpenses: number;
    meshAmount: number;
    contractAmount: number;
    workColumns: Array<WorkColumn>;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum Role {
    admin = "admin",
    contractOnly = "contractOnly",
    attendanceOnly = "attendanceOnly",
    viewOnly = "viewOnly"
}
export enum UserStatus {
    revoked = "revoked",
    pending = "pending",
    approved = "approved"
}
export interface backendInterface {
    addAdvance(contractId: bigint, labourId: bigint, amount: number, note: string): Promise<{
        __kind__: "ok";
        ok: Advance;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addContract(name: string, multiplier: number, contractAmount: number, machineExpenses: number, bedAmount: number, paperAmount: number, meshAmount: number | null): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addLabour(name: string, employeeId: string, joinDate: string): Promise<{
        __kind__: "ok";
        ok: Labour;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addWorkColumn(contractId: bigint, name: string, workType: string): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }>;
    approveUser(username: string, role: Role): Promise<void>;
    batchSaveAttendance(updates: Array<[bigint, bigint, string, AttendanceValue]>): Promise<Array<boolean>>;
    createUser(username: string, password: string, role: Role): Promise<boolean>;
    deleteAdvance(id: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteContract(id: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    execute(qJson: string): Promise<Result>;
    exportData(): Promise<string>;
    getActiveLabours(): Promise<Array<Labour>>;
    getAdvances(): Promise<Array<Advance>>;
    getAdvancesByContract(contractId: bigint): Promise<Array<Advance>>;
    getAllAttendance(): Promise<Array<AttendanceRecord>>;
    getAttendance(contractId: bigint): Promise<Array<AttendanceRecord>>;
    getCallerRole(): Promise<Role | null>;
    getCallerStatus(): Promise<UserStatus>;
    getContracts(): Promise<Array<Contract>>;
    getLabours(): Promise<Array<Labour>>;
    importData(json: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listUsers(): Promise<Array<UserInfo>>;
    login(creds: Credentials): Promise<AuthResult | null>;
    logout(): Promise<void>;
    markContractSettled(id: bigint, settled: boolean): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeWorkColumn(contractId: bigint, columnId: string): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }>;
    revokeAccess(username: string): Promise<void>;
    schema(): Promise<string>;
    setAttendance(contractId: bigint, labourId: bigint, columnId: string, value: AttendanceValue): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setUserRole(username: string, role: Role): Promise<void>;
    updateAdvance(id: bigint, amount: number, note: string): Promise<{
        __kind__: "ok";
        ok: Advance;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateContract(id: bigint, name: string, multiplier: number, contractAmount: number, machineExpenses: number, bedAmount: number, paperAmount: number, meshAmount: number | null): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateLabour(id: bigint, name: string, employeeId: string, joinDate: string, isActive: boolean): Promise<{
        __kind__: "ok";
        ok: Labour;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateUserCredentials(oldUsername: string, newUsername: string, newPassword: string | null): Promise<boolean>;
    updateWorkColumn(contractId: bigint, columnId: string, name: string): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Advance as _Advance, AttendanceRecord as _AttendanceRecord, AttendanceValue as _AttendanceValue, AuthResult as _AuthResult, Cell as _Cell, Contract as _Contract, Labour as _Labour, Result as _Result, Role as _Role, UserInfo as _UserInfo, UserStatus as _UserStatus, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdvance(arg0: bigint, arg1: bigint, arg2: number, arg3: string): Promise<{
        __kind__: "ok";
        ok: Advance;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdvance(arg0, arg1, arg2, arg3);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdvance(arg0, arg1, arg2, arg3);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addContract(arg0: string, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number | null): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addContract(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg6));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContract(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg6));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addLabour(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Labour;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addLabour(arg0, arg1, arg2);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLabour(arg0, arg1, arg2);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async addWorkColumn(arg0: bigint, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkColumn(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkColumn(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveUser(arg0: string, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchSaveAttendance(arg0: Array<[bigint, bigint, string, AttendanceValue]>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor.batchSaveAttendance(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchSaveAttendance(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: Role): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteAdvance(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdvance(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdvance(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContract(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContract(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContract(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportData();
            return result;
        }
    }
    async getActiveLabours(): Promise<Array<Labour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveLabours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveLabours();
            return result;
        }
    }
    async getAdvances(): Promise<Array<Advance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvances();
            return result;
        }
    }
    async getAdvancesByContract(arg0: bigint): Promise<Array<Advance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancesByContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancesByContract(arg0);
            return result;
        }
    }
    async getAllAttendance(): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAttendance();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAttendance();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendance(arg0: bigint): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerRole(): Promise<Role | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRole();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRole();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerStatus(): Promise<UserStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStatus();
                return from_candid_UserStatus_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStatus();
            return from_candid_UserStatus_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContracts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContracts();
            return result;
        }
    }
    async getLabours(): Promise<Array<Labour>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabours();
            return result;
        }
    }
    async importData(arg0: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.importData(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importData(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: Credentials): Promise<AuthResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout();
            return result;
        }
    }
    async markContractSettled(arg0: bigint, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markContractSettled(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContractSettled(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeWorkColumn(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorkColumn(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorkColumn(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async revokeAccess(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeAccess(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setAttendance(arg0: bigint, arg1: bigint, arg2: string, arg3: AttendanceValue): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAttendance(arg0, arg1, arg2, to_candid_AttendanceValue_n9(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAttendance(arg0, arg1, arg2, to_candid_AttendanceValue_n9(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserRole(arg0: string, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateAdvance(arg0: bigint, arg1: number, arg2: string): Promise<{
        __kind__: "ok";
        ok: Advance;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdvance(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdvance(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContract(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number | null): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLabour(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<{
        __kind__: "ok";
        ok: Labour;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLabour(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLabour(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserCredentials(arg0: string, arg1: string, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserCredentials(arg0, arg1, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserCredentials(arg0, arg1, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateWorkColumn(arg0: bigint, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Contract;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkColumn(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkColumn(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AttendanceRecord_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceValue_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceValue): AttendanceValue {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResult_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserInfo_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserInfo): UserInfo {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AuthResult]): AuthResult | null {
    return value.length === 0 ? null : from_candid_AuthResult_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n14(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n18(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _AttendanceValue;
    labourId: bigint;
    contractId: bigint;
    columnId: string;
}): {
    value: AttendanceValue;
    labourId: bigint;
    contractId: bigint;
    columnId: string;
} {
    return {
        value: from_candid_AttendanceValue_n23(_uploadFile, _downloadFile, value.value),
        labourId: value.labourId,
        contractId: value.contractId,
        columnId: value.columnId
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UserStatus;
    username: string;
    name: [] | [string];
    role: _Role;
    email: [] | [string];
}): {
    status: UserStatus;
    username: string;
    name?: string;
    role: Role;
    email?: string;
} {
    return {
        status: from_candid_UserStatus_n28(_uploadFile, _downloadFile, value.status),
        username: value.username,
        name: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.name)),
        role: from_candid_Role_n26(_uploadFile, _downloadFile, value.role),
        email: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UserStatus;
    username: string;
    role: _Role;
}): {
    status: UserStatus;
    username: string;
    role: Role;
} {
    return {
        status: from_candid_UserStatus_n28(_uploadFile, _downloadFile, value.status),
        username: value.username,
        role: from_candid_Role_n26(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Advance;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Advance;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    absent: null;
} | {
    partial: number;
}): {
    __kind__: "present";
    present: null;
} | {
    __kind__: "absent";
    absent: null;
} | {
    __kind__: "partial";
    partial: number;
} {
    return "present" in value ? {
        __kind__: "present",
        present: value.present
    } : "absent" in value ? {
        __kind__: "absent",
        absent: value.absent
    } : "partial" in value ? {
        __kind__: "partial",
        partial: value.partial
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    contractOnly: null;
} | {
    attendanceOnly: null;
} | {
    viewOnly: null;
}): Role {
    return "admin" in value ? Role.admin : "contractOnly" in value ? Role.contractOnly : "attendanceOnly" in value ? Role.attendanceOnly : "viewOnly" in value ? Role.viewOnly : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revoked: null;
} | {
    pending: null;
} | {
    approved: null;
}): UserStatus {
    return "revoked" in value ? UserStatus.revoked : "pending" in value ? UserStatus.pending : "approved" in value ? UserStatus.approved : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Contract;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Contract;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Labour;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Labour;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserInfo>): Array<UserInfo> {
    return value.map((x)=>from_candid_UserInfo_n31(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceValue_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceValue): _AttendanceValue {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, bigint, string, AttendanceValue]): [bigint, bigint, string, _AttendanceValue] {
    return [
        value[0],
        value[1],
        value[2],
        to_candid_AttendanceValue_n9(_uploadFile, _downloadFile, value[3])
    ];
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "present";
    present: null;
} | {
    __kind__: "absent";
    absent: null;
} | {
    __kind__: "partial";
    partial: number;
}): {
    present: null;
} | {
    absent: null;
} | {
    partial: number;
} {
    return value.__kind__ === "present" ? {
        present: value.present
    } : value.__kind__ === "absent" ? {
        absent: value.absent
    } : value.__kind__ === "partial" ? {
        partial: value.partial
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    contractOnly: null;
} | {
    attendanceOnly: null;
} | {
    viewOnly: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.contractOnly ? {
        contractOnly: null
    } : value == Role.attendanceOnly ? {
        attendanceOnly: null
    } : value == Role.viewOnly ? {
        viewOnly: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, bigint, string, AttendanceValue]>): Array<[bigint, bigint, string, _AttendanceValue]> {
    return value.map((x)=>to_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
