import { useState } from "react";
import {
  ArrowLeft, ArrowRight, Bell, CalendarDays, ChevronDown, ChevronRight, ClipboardCheck,
  FileText, Filter, Home, LockKeyhole, Menu, MoreHorizontal, Paperclip, Plus, Search,
  Settings, User, Users, WalletCards, X, Eye, EyeOff, LogOut, MapPin, BriefcaseBusiness
} from "lucide-react";
import "./rossie-fresh.css";

type Screen = "splash"|"login"|"signup"|"pending"|"home"|"contracts"|"attendance"|"labour"|"payments"|"advances"|"admin"|"more";
const contracts = [
  {name:"Ocean Builders Ltd.", code:"RC-001", dates:"Jan 15, 2025 – Dec 31, 2025", labour:"24 Labourers", location:"Bengaluru, Karnataka", status:"Active"},
  {name:"Sunrise Infra Pvt. Ltd.", code:"RC-002", dates:"Feb 01, 2025 – Nov 30, 2025", labour:"18 Labourers", location:"Mysuru, Karnataka", status:"Active"},
  {name:"Greenfield Projects", code:"RC-003", dates:"Mar 10, 2025 – Dec 15, 2025", labour:"32 Labourers", location:"Hassan, Karnataka", status:"Active"},
  {name:"Vijaya Constructions", code:"RC-004", dates:"Jan 05, 2025 – Sep 30, 2025", labour:"16 Labourers", location:"Bengaluru, Karnataka", status:"Completed"},
];
const labour = [
  ["Ramesh Kumar","L-001","Present","08:12"],["Suresh Babu","L-002","Present","08:20"],
  ["Lakshmi Devi","L-003","Absent","—"],["Mohan Das","L-004","Present","08:15"],["Shankar R","L-005","Present","08:10"]
];
const nav=[["home","Home",Home],["contracts","Contracts",FileText],["attendance","Attendance",ClipboardCheck],["payments","Payments",WalletCards],["more","More",Menu]] as const;

export default function RossieFreshApp(){
  const [screen,setScreen]=useState<Screen>("splash");
  const [showPass,setShowPass]=useState(false);
  const [contract,setContract]=useState(contracts[0]);
  const [tab,setTab]=useState("All");
  const [query,setQuery]=useState("");
  const go=(s:Screen)=>setScreen(s);
  if(screen==="splash") return <div className="rf-screen rf-splash" onClick={()=>go("login")}><div className="rf-splash-shape rf-s1"/><div className="rf-splash-shape rf-s2"/><Brand/><div className="rf-splash-copy">Better Workforce.<br/>Brighter Tomorrow.</div></div>;
  if(screen==="login") return <Auth mode="login" showPass={showPass} setShowPass={setShowPass} onBack={()=>go("splash")} onSubmit={()=>go("home")} onSignup={()=>go("signup")}/>;
  if(screen==="signup") return <Auth mode="signup" showPass={showPass} setShowPass={setShowPass} onBack={()=>go("login")} onSubmit={()=>go("pending")} onSignup={()=>go("login")}/>;
  if(screen==="pending") return <div className="rf-screen rf-auth"><div className="rf-orb rf-orb-blue"/><div className="rf-orb rf-orb-orange"/><div className="rf-pending"><div className="rf-paper-plane">➤</div><h1>Request sent to admin</h1><p>Your account will be available<br/>after admin approval.</p><button className="rf-primary" onClick={()=>go("login")}>Back to login</button></div></div>;
  return <div className="rf-app"><header className="rf-header"><button className="rf-iconbtn"><Menu size={20}/></button><div className="rf-title">{screen==="home"?"":screen[0].toUpperCase()+screen.slice(1)}</div><button className="rf-iconbtn"><Bell size={19}/></button></header>{screen==="home"&&<HomeScreen go={go}/>} {screen==="contracts"&&<ContractsScreen go={go} contract={contract} setContract={setContract} query={query} setQuery={setQuery}/>} {screen==="attendance"&&<AttendanceScreen query={query} setQuery={setQuery}/>} {screen==="labour"&&<LabourScreen go={go}/>} {screen==="payments"&&<PaymentsScreen contract={contract} tab={tab} setTab={setTab}/>} {screen==="advances"&&<AdvancesScreen contract={contract}/>} {screen==="admin"&&<AdminScreen query={query} setQuery={setQuery}/>} {screen==="more"&&<MoreScreen go={go}/>}<BottomNav screen={screen} go={go}/></div>;
}

function Brand(){return <div className="rf-brand"><div className="rf-logo"><CalendarDays size={39}/></div><div className="rf-brand-name">Rossie</div><div className="rf-brand-sub">Attendance Management</div></div>}
function Auth({mode,showPass,setShowPass,onBack,onSubmit,onSignup}:{mode:"login"|"signup";showPass:boolean;setShowPass:(v:boolean)=>void;onBack:()=>void;onSubmit:()=>void;onSignup:()=>void}){return <div className="rf-screen rf-auth"><div className="rf-auth-wave rf-w1"/><div className="rf-auth-wave rf-w2"/><div className="rf-auth-card"><button className="rf-back" onClick={onBack}><ArrowLeft size={20}/></button><Brand/><h2>{mode==="login"?"Sign in":"Create account"}</h2><p className="rf-muted">{mode==="login"?"":"Join Rossie and manage your workforce effortlessly."}</p><label><User size={18}/><input placeholder={mode==="login"?"Mobile number or username":"Mobile number"}/></label><label><LockKeyhole size={18}/><input type={showPass?"text":"password"} placeholder={mode==="login"?"Password":"Create password"}/><button className="rf-eye" onClick={()=>setShowPass(!showPass)}>{showPass?<EyeOff size={17}/>:<Eye size={17}/>}</button></label>{mode==="signup"&&<label><LockKeyhole size={18}/><input type="password" placeholder="Confirm password"/><Eye size={17}/></label>}{mode==="login"&&<label className="rf-check"><input type="checkbox" defaultChecked/> <span>Keep me signed in</span></label>}<button className={mode==="login"?"rf-primary":"rf-orange"} onClick={onSubmit}>{mode==="login"?"SIGN IN  →":"CREATE ACCOUNT"}</button><div className="rf-auth-link">{mode==="login"?<>New here? <button onClick={onSignup}>Create account</button></>:<button onClick={onSignup}>Back to login</button>}</div></div></div>}

function HomeScreen({go}:{go:(s:Screen)=>void}){return <main className="rf-content"><div className="rf-profile"><div className="rf-avatar">RK</div><div><small>Hello,</small><strong>Ravi Kumar</strong></div><Bell size={21}/></div><div className="rf-card rf-today"><div><b>Today's Attendance</b><small>10 Sep 2025</small></div><span className="rf-badge green">Present</span></div><div className="rf-stats"><Stat title="Total" value="24" cls="blue"/><Stat title="Present" value="20" cls="green"/><Stat title="Absent" value="4" cls="red"/><Stat title="On Leave" value="0" cls="purple"/></div><h3>Quick Actions</h3><div className="rf-actions"><Action icon={<ClipboardCheck/>} text="Mark Attendance" onClick={()=>go("attendance")}/><Action icon={<FileText/>} text="View Contracts" onClick={()=>go("contracts")}/><Action icon={<WalletCards/>} text="Payments" onClick={()=>go("payments")}/><Action icon={<WalletCards/>} text="Advances" onClick={()=>go("advances")}/></div></main>}
function Stat({title,value,cls}:{title:string;value:string;cls:string}){return <div className={"rf-stat "+cls}><small>{title}</small><b>{value}</b></div>}
function Action({icon,text,onClick}:{icon:React.ReactNode;text:string;onClick:()=>void}){return <button className="rf-action" onClick={onClick}>{icon}<span>{text}</span></button>}
function ContractsScreen({go,contract,setContract,query,setQuery}:{go:(s:Screen)=>void;contract:any;setContract:(v:any)=>void;query:string;setQuery:(v:string)=>void}){const list=contracts.filter(c=>c.name.toLowerCase().includes(query.toLowerCase()));return <main className="rf-content"><div className="rf-screenbar"><b>Contracts</b><Filter size={18}/></div><div className="rf-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search contracts..."/></div><div className="rf-pills"><span className="active">All (5)</span><span>Active (4)</span><span>Completed (1)</span></div>{list.map(c=><button className="rf-contract" key={c.code} onClick={()=>{setContract(c);go("labour")}}><div className="rf-contract-top"><div className="rf-contract-icon"><BriefcaseBusiness size={18}/></div><div><b>{c.name}</b><small>{c.code}</small></div><span className={"rf-badge "+(c.status==="Active"?"green":"gray")}>{c.status}</span></div><small>◷ {c.dates}</small><small>♙ {c.labour}</small><small>⌖ {c.location}</small><ChevronRight className="rf-contract-arrow" size={18}/></button>)}<button className="rf-fab"><Plus/></button></main>}
function AttendanceScreen({query,setQuery}:{query:string;setQuery:(v:string)=>void}){return <main className="rf-content"><div className="rf-date"><button><ArrowLeft/></button><b>▣ 10 Sep 2025</b><button><ArrowRight/></button></div><div className="rf-stats three"><Stat title="Total" value="24" cls="blue"/><Stat title="Present" value="20" cls="green"/><Stat title="Absent" value="4" cls="red"/></div><div className="rf-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search labourers..."/></div><div className="rf-table-head"><span>Name / ID</span><span>Status</span><span>Time</span></div>{labour.map(([name,id,status,time])=><div className="rf-labour-row" key={id}><div className="rf-mini-avatar">{name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><b>{name}</b><small>{id}</small></div><span className={"rf-badge "+(status==="Present"?"green":"red")}>{status}</span><small>{time}</small></div>)}</main>}
function LabourScreen({go}:{go:(s:Screen)=>void}){return <main className="rf-content"><div className="rf-detail-head"><div className="rf-avatar large">RK</div><div><b>Ramesh Kumar</b><small>L-001 · Male · 28 yrs</small></div><MoreHorizontal/></div><div className="rf-tabs"><span className="active">Profile</span><span>Attendance</span><span>Payments</span><span>Advances</span></div><div className="rf-detail-card"><Detail icon={<User/>} label="Father Name" value="Raju Kumar"/><Detail icon={<User/>} label="Mobile Number" value="+91 98765 43210"/><Detail icon={<MapPin/>} label="Address" value="Hassan, Karnataka"/><Detail icon={<BriefcaseBusiness/>} label="Work Type" value="Bed"/><Detail icon={<CalendarDays/>} label="Join Date" value="15 Jan 2025"/><Detail icon={<CalendarDays/>} label="Experience" value="2 years"/></div><button className="rf-primary" onClick={()=>go("labour")}>✎ Edit</button></main>}
function Detail({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rf-detail"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>}
function PaymentsScreen({contract,tab,setTab}:{contract:any;tab:string;setTab:(v:string)=>void}){return <main className="rf-content"><Select text={contract.name+" ("+contract.code+")"}/><div className="rf-stats two"><Stat title="Total Paid" value="₹ 48,750" cls="green"/><Stat title="Pending" value="₹ 12,500" cls="orange"/></div><div className="rf-pills center">{["All","Paid","Pending"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{["Sep 2025","Aug 2025","Jul 2025","Jun 2025"].map((m,i)=><div className="rf-list-row" key={m}><div><b>{m}</b><small>₹ 8,500</small></div><span className={"rf-badge "+(i===3?"orange":"green")}>{i===3?"Pending":"Paid"}</span></div>)}</main>}
function AdvancesScreen({contract}:{contract:any}){return <main className="rf-content"><Select text={contract.name+" ("+contract.code+")"}/><div className="rf-stats two"><Stat title="Total Advances" value="₹ 15,000" cls="blue"/><Stat title="Remaining" value="₹ 7,500" cls="purple"/></div>{["Ravi Kumar","Suresh Babu","Lakshmi Devi"].map((n,i)=><div className="rf-list-row" key={n}><div><b>{n}</b><small>L-00{i+1} · {12+i*10} May 2025</small></div><strong>₹ 5,000</strong><span className={"rf-badge "+(i===2?"orange":"green")}>{i===2?"Pending":"Paid"}</span></div>)}</main>}
function Select({text}:{text:string}){return <div className="rf-select"><small>Select Contract</small><b>{text}</b><ChevronDown size={17}/></div>}
function AdminScreen({query,setQuery}:{query:string;setQuery:(v:string)=>void}){return <main className="rf-content"><div className="rf-admin-card"><div className="rf-avatar">♟</div><div><b>Active Accounts</b><small>12<br/>Out of 16 total accounts</small></div><ChevronRight/></div><div className="rf-admin-card orange-card"><div className="rf-avatar orange">◷</div><div><b>Pending Requests</b><small>3<br/>Awaiting admin approval</small></div><ChevronRight/></div><h3>User Accounts</h3><div className="rf-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name or mobile..."/><Filter size={17}/></div>{["Ravi Kumar","Suresh Patel","Meena Devi","Admin User"].map((n,i)=><div className="rf-user-row" key={n}><div className="rf-avatar small">{n.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><b>{n}</b><small>+91 98765 43210</small></div><span className={"rf-badge "+(i===3?"orange":"green")}>{i===3?"Admin":"Worker"}</span><ChevronRight size={16}/></div>)}</main>}
function MoreScreen({go}:{go:(s:Screen)=>void}){return <main className="rf-content"><div className="rf-more-profile"><div className="rf-avatar large">RK</div><div><b>Ravi Kumar</b><small>Worker</small></div><ChevronRight/></div>{["My Profile","Change Password","Settings","Help & Support","About"].map((x,i)=><button className="rf-menu-row" key={x}><span>{i===0?<User/>:i===1?<LockKeyhole/>:i===2?<Settings/>:<FileText/>}</span>{x}<ChevronRight/></button>)}<button className="rf-logout" onClick={()=>go("login")}><LogOut size={17}/> Logout</button></main>}
function BottomNav({screen,go}:{screen:Screen;go:(s:Screen)=>void}){return <nav className="rf-bottom">{nav.map(([id,label,Icon])=><button className={screen===id?"active":""} key={id} onClick={()=>go(id as Screen)}><Icon size={19}/><small>{label}</small></button>)}</nav>}
